### PR TITLE
Update index.mdx

### PR DESCRIPTION
**Pull request by kacperpaczos**
Added missing library on Ubuntu 22.04 during the app build (Rust's crafts compile stage).

#### What kind of changes does this PR include?
- New or updated content
- Changes to the docs site code

#### Description

- This PR addresses the issue related to a missing library during the app build on Ubuntu 22.04 in Rust's crafts compile stage.
- The changes involve updating the documentation to reflect the necessary addition of the library.
- No visual changes have been made.

### CODE REVIEW

**Comment by FabianLars** [comment]
webkitgtk is already present in line 34 (the same line as `sudo apt...`) and libsoup and jsc are direct dependencies of it so i assume it was just a copy paste mistake that lead to the compilation error?
